---
dockitems_remove_all: false
dockitems_remove:
  - Mail
  - Safari
  - Siri
  - Contacts
  - Notes
  - Reminders
  - Maps
  - Photos
  - Messages
  - FaceTime
  - Music
  - TV
  - App Store
  - System Preferences
  - Calendar
  - Terminal
  - Podcasts
  - Keynote
  - Pages
  - Numbers
  - "System Settings"
  - OmniFocus

dockitems_persist:
  - name: Launchpad
    path: "/Applications/Launchpad.app"
    pos: 1
  - name: Commander One
    path: "/Applications/SetApp/Commander One.app"
    pos: 2
  - name: Canary Mail
    path: "/Applications/SetApp/Canary Mail.app"
    pos: 3
  - name: Calendar
    path: "/System/Applications/Calendar.app"
    pos: 4
  - name: Ivory
    path: "/Applications/Ivory.app"
    pos: 5
  - name: ClickUp
    path: "/Applications/ClickUp.app"
    pos: 6
  - name: Visual Studio Code
    path: "/Applications/Visual Studio Code.app"
    pos: 7
  - name: SQLPro Studio
    path: "/Applications/SetApp/SQLPro Studio.app"
    pos: 8
