---
homebrew_taps:
  - homebrew/cask-drivers
  - homebrew/cask-fonts
  - homebrew/cask-versions
  - buo/cask-upgrade
  - hashicorp/tap
  - pulumi/tap
  - updatecli/updatecli

homebrew_installed_packages:
  - antidote
  - asciidoctor
  - awscli
  - azure-cli
  - exercism
  - gh
  - gnu-tar
  - gnupg
  - go
  - graphviz
  - gzip
  - helm
  - httpie
  - hugo
  - jq
  - pinentry-mac
  - plantuml
  - poetry
  - pre-commit
  - protobuf
  - pstree
  - starship
  - volta
  - watch
  - pulumi/tap/pulumi
  - pulumi/tap/crd2pulumi
  - pulumi/tap/kube2pulumi
  - pulumi/tap/pulumictl
  - updatecli/updatecli/updatecli

homebrew_uninstalled_packages:
  - fzf
  - dotnet
  - pulumi/tap/tf2pulumi

homebrew_cask_apps:
  - corretto
  - discord
  - docker
  - element
  - elgato-stream-deck
  - firefox
  - focusrite-control
  - font-roboto-mono-nerd-font
  - gitter
  - google-chrome
  - insomnia
  - obsidian

mas_email: ""
mas_password: ""
mas_installed_apps:
  - id: 824171161
    name: "Affinity Designer"
  - id: 406056744
    name: "Evernote"
  - id: 682658836
    name: "GarageBand"
  - id: 408981434
    name: "iMovie"
  - id: 6444602274
    name: "Ivory"
  - id: 409183694
    name: "Keynote"
  - id: 441258766
    name: "Magnet"
  - id: 409203825
    name: "Numbers"
  - id: 409201541
    name: "Pages"
  - id: 403504866
    name: "PCalc"
  - id: 899247664
    name: "Testflight"
  - id: 1482454543
    name: "Twitter"
  - id: 497799835
    name: "XCode"

mas_upgrade_all_apps: false
mas_signin_dialog: false

# Whether to install dockutil or not
dockutil_install: true
# Which homebrew cask to install for dockutil
dockutil_homebrew_cask: hpedrorodrigues/tools/dockutil
dockitems_remove_all: false
dockitems_remove:
  - Mail
  - Safari
  - Siri
  - Contacts
  - Notes
  - Reminders
  - Maps
  - Photos
  - Messages
  - FaceTime
  - Music
  - TV
  - App Store
  - System Preferences
  - Calendar
  - Terminal
  - Podcasts
  - Keynote
  - Pages
  - Numbers
  - "System Settings"
  - OmniFocus
  - Twitter

dockitems_persist:
  - name: Launchpad
    path: "/Applications/Launchpad.app"
    pos: 1
  - name: Commander One
    path: "/Applications/SetApp/Commander One.app"
    pos: 2
  - name: Thunderbird
    path: "/Applications/Thunderbird.app"
    pos: 3
  - name: Calendar
    path: "/System/Applications/Calendar.app"
    pos: 4
  - name: Ivory
    path: "/Applications/Ivory.app"
    pos: 5
  - name: ClickUp
    path: "/Applications/ClickUp.app"
    pos: 6
  - name: Visual Studio Code
    path: "/Applications/Visual Studio Code.app"
    pos: 7
  - name: SQLPro Studio
    path: "/Applications/SetApp/SQLPro Studio.app"
    pos: 8

dotfiles_repo: "https://github.com/ringods/dotfiles.git"
dotfiles_repo_version: master
dotfiles_repo_local_destination: "~/Projects/personal/dotfiles"
dotfiles_repo_accept_hostkey: true
dotfiles_home: "~"
dotfiles_files:
  - .gitconfig
  - .gitignore
  - .zshrc.local
  - .zsh_plugins.txt
