---
galaxy_info:
  author: Ringo De Smet
  description: Minimal macOS setup.
  company: None

  license: MIT

  min_ansible_version: 2.2

  platforms:
    - name: MacOSX
      versions:
        - 'all'

  galaxy_tags:
    - osx
    - configuration

dependencies:
  - role: geerlingguy.mac.homebrew
    vars:
      homebrew_installed_packages:
        - coreutils
        - curl
        - git
        - git-lfs
        - wget
        - zsh
  - role: geerlingguy.mac.mas
    vars:
      mas_installed_apps:
        - id: 497799835
          name: "XCode"
      # mas_uninstalled_apps:
      #   - id: 1482454543
      #     name: "Twitter"
