---
galaxy_info:
  author: Ringo De Smet
  description: Additional setup for my personal MacBook Pro
  company: None

  license: MIT

  min_ansible_version: "9.0"

  platforms:
    - name: MacOSX
      versions:
        - "all"

  galaxy_tags:
    - osx
    - configuration

dependencies:
  - role: geerlingguy.mac.homebrew
    vars:
      homebrew_cask_appdir: /Applications
      homebrew_installed_packages:
        - cilium-cli
        - rustup
        - vercel-cli
        - hashicorp/tap/packer
      homebrew_uninstalled_packages:
        - podman
      homebrew_cask_apps:
        - affinity-designer
        - affinity-photo
        - affinity-publisher
        - balenaetcher
        - corretto@8
        - corretto@11
        - libreoffice
        - little-snitch
        - micro-snitch
        - orbstack
        - paragon-extfs
        - raspberry-pi-imager
        - responsively
#      homebrew_cask_uninstalled_apps:
  - role: geerlingguy.mac.mas
    vars:
      mas_installed_apps:
        - id: 406056744
          name: "Evernote"
        - id: 682658836
          name: "GarageBand"
        - id: 408981434
          name: "iMovie"
        - id: 899247664
          name: "Testflight"
  - role: geerlingguy.mac.dock
