---
galaxy_info:
  author: Ringo De Smet
  description: Additional setup for my personal MacBook Pro
  company: None

  license: MIT

  min_ansible_version: 2.2

  platforms:
    - name: MacOSX
      versions:
        - 'all'

  galaxy_tags:
    - osx
    - configuration

dependencies:
  - role: geerlingguy.mac.homebrew
    vars:
      homebrew_cask_appdir: /Applications
      homebrew_installed_packages:
        - cilium-cli
        - rustup
        - vercel-cli
        - hashicorp/tap/packer
      homebrew_uninstalled_packages:
        - podman
      homebrew_cask_apps:
        - balenaetcher
        - dropbox
        - libreoffice
        - little-snitch
        - micro-snitch
        - orbstack
        - paragon-extfs
        - raspberry-pi-imager
        - responsively
        - zed
      homebrew_cask_uninstalled_apps:
        - docker
        - google-cloud-sdk
        - podman-desktop
        - trainerroad
        - isen-ng/dotnet-sdk-versions/dotnet-sdk6-0-400
        - isen-ng/dotnet-sdk-versions/dotnet-sdk7-0-200
  - role: geerlingguy.mac.mas
    vars:
      mas_installed_apps:
        - id: 824171161
          name: "Affinity Designer"
        - id: 406056744
          name: "Evernote"
        - id: 682658836
          name: "GarageBand"
        - id: 408981434
          name: "iMovie"
        - id: 899247664
          name: "Testflight"
