---
galaxy_info:
  author: Ringo De Smet
  description: Additional setup for my personal MacBook Pro
  company: None

  license: MIT

  min_ansible_version: "9.0"

  platforms:
    - name: MacOSX
      versions:
        - "all"

  galaxy_tags:
    - osx
    - configuration

dependencies:
  - role: geerlingguy.mac.homebrew
    vars:
      homebrew_cask_appdir: /Applications
#      homebrew_installed_packages:
#      homebrew_uninstalled_packages:
      homebrew_cask_apps:
        - corretto@8
        - corretto@11
        - libreoffice
        - orbstack
        - responsively
#      homebrew_cask_uninstalled_apps:
  - role: geerlingguy.mac.mas
    vars:
      mas_installed_apps:
        - id: 406056744
          name: "Evernote"
  - role: geerlingguy.mac.dock
