---
homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - homebrew/cask-drivers
  - buo/cask-upgrade
  - dagger/tap
  - hashicorp/tap
  - pulumi/tap

homebrew_installed_packages:
  - asciidoctor
  - awscli
  - azure-cli
  - cfssl
  - coreutils
  - curl
  - direnv
  - exercism
  - fzf
  - git
  - git-lfs
  - gnu-tar
  - gnupg
  - go
  - graphviz
  - gzip
  - helm
  - httpie
  - hugo
  - jq
  - pinentry-mac
  - plantuml
  - poetry
  - pre-commit
  - protobuf
  - pstree
  - volta
  - watch
  - wget
  - zsh
  - hashicorp/tap/packer
  - hashicorp/tap/terraform
  - dagger/tap/dagger
  - pulumi/tap/pulumi
  - pulumi/tap/crd2pulumi
  - pulumi/tap/kube2pulumi
  - pulumi/tap/pulumictl
  - pulumi/tap/tf2pulumi

homebrew_uninstalled_packages:
  - pulumi

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - 1password
  - 1password-cli
  - alfred
  - balenaetcher
  - corretto
  - discord
  - docker
  - dotnet-sdk
  - dropbox
  - elgato-stream-deck
  - firefox
  #- focusrite-control <- Needs Rosetta / Follow up on Twitter with @WeAreFocusrite
  - gitter
  - google-chrome
  - google-cloud-sdk
  - google-drive
  - insomnia
  - iterm2
  #- jetbrains-toolbox <- Will I use Fleet or goLand?
  - keybase
  - little-snitch
  - micro-snitch
  - microsoft-teams
  - obsidian
  - omnifocus
  - paragon-extfs
  - raspberry-pi-imager
  - setapp
  - signal
  - slack
  - spotify
  - telegram
  - trainerroad
  - viscosity
  - visual-studio-code
  - vlc
  - whatsapp
  - zoom

homebrew_cask_uninstalled_apps:
  - ableton-live-lite
  - dash
  - font-powerline-symbols
  - font-roboto-mono-for-powerline
  - garmin-express
  - visualvm
  - vmware-fusion
  - zoomus

mas_email: ""
mas_password: ""
mas_installed_apps:
  - id: 824171161
    name: "Affinity Designer"
  - id: 406056744
    name: "Evernote"
  - id: 682658836
    name: "GarageBand"
  - id: 408981434
    name: "iMovie"
  - id: 409183694
    name: "Keynote"
  - id: 441258766
    name: "Magnet"
  - id: 409203825
    name: "Numbers"
  - id: 409201541
    name: "Pages"
  - id: 403504866
    name: "PCalc"
  - id: 1176895641
    name: "Spark"
  - id: 497799835
    name: "XCode"

mas_upgrade_all_apps: true
mas_signin_dialog: false

# yamllint disable-line rule:line-length
dockutil_url: https://raw.githubusercontent.com/kcrawford/dockutil/master/scripts/dockutil
dockutil_install_path: /usr/local/bin/dockutil

dockitems_remove_all: false

dockitems_remove:
  - Mail
  - Safari
  - Siri
  - Contacts
  - Notes
  - Reminders
  - Maps
  - Photos
  - Messages
  - FaceTime
  - Music
  - TV
  - App Store
  - System Preferences
  - Calendar
  - Terminal
  - Podcasts
  - Keynote
  - Pages
  - Numbers
  - "System Settings"

dockitems_persist:
  - name: Launchpad
    path: "/Applications/Launchpad.app"
    pos: 1
  - name: Commander One
    path: "/Applications/SetApp/Commander One.app"
    pos: 2
  - name: Spark
    path: "/Applications/Spark.app"
    pos: 3
  - name: Calendar
    path: "/System/Applications/Calendar.app"
    pos: 4
  - name: OmniFocus
    path: "/Applications/OmniFocus.app"
    pos: 5
  - name: Visual Studio Code
    path: "/Applications/Visual Studio Code.app"
    pos: 6
  - name: SQLPro Studio
    path: "/Applications/SetApp/SQLPro Studio.app"
    pos: 7

dotfiles_repo: "https://github.com/ringods/dotfiles.git"
dotfiles_repo_version: master
dotfiles_repo_local_destination: "~/Projects/personal/dotfiles"
dotfiles_repo_accept_hostkey: true
dotfiles_home: "~"
dotfiles_files:
  - .gitconfig
  - .gitignore
  - .zshrc.local
