---
homebrew_installed_packages:
  - asciidoctor
  - awscli
  - azure-cli
  - cfssl
  - coreutils
  - curl
  - dep
  - direnv
  - elixir
  - elm
  - elm-format
  - erlang
  - exercism
  - fzf
  - git
  - git-lfs
  - gnu-tar
  - go
  - gpg
  - graphviz
  - gzip
  - helm
  - httpie
  - hugo
  - jq
  - node@12
  - plantuml
  - pre-commit
  - protobuf
  - pstree
  - pulumi
  - pyenv-virtualenv
  - watch
  - wget
  - yarn
  - zsh
  - hashicorp/tap/packer
  - hashicorp/tap/terraform
  - nektos/tap/act

homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - homebrew/cask-drivers
  - homebrew/cask-eid
  - homebrew/cask-fonts
  - buo/cask-upgrade
  - nektos/tap
  - hashicorp/tap

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - 1password
  - ableton-live-lite
  - alfred
  - balenaetcher
  - corretto
  - dash
  - discord
  - docker
  - dotnet-sdk
  - dropbox
  - firefox
  - focusrite-control
  - font-powerline-symbols
  - font-roboto-mono-for-powerline
  - garmin-express
  - gitter
  - google-cloud-sdk
  - insomnia
  - iterm2
  - keybase
  - little-snitch
  - micro-snitch
  - microsoft-teams
  - omnifocus
  - signal
  - slack
  - spectrum
  - spotify
  - telegram
  - trainerroad
  - vagrant
  - virtualbox
  - virtualbox-extension-pack
  - viscosity
  - visual-studio-code
  - vlc
  - whatsapp
  - zoomus

mas_email: ""
mas_password: ""
mas_installed_apps:
  - { id: 824171161, name: "Affinity Designer" }
  - { id: 1205882554, name: "Cliq - Team communication" }
  - { id: 411643860, name: "DaisyDisk" }
  - { id: 406056744, name: "Evernote" }
  - { id: 682658836, name: "GarageBand" }
  - { id: 408981434, name: "iMovie" }
  - { id: 409183694, name: "Keynote" }
  - { id: 441258766, name: "Magnet" }
  - { id: 409203825, name: "Numbers" }
  - { id: 409201541, name: "Pages" }
  - { id: 403504866, name: "PCalc" }
  - { id: 1176895641, name: "Spark" }
  - { id: 1384080005, name: "Tweetbot 3 for Twitter" }
  - { id: 810962929, name: "Writer - Online Word Processor" }
  - { id: 497799835, name: "XCode" }
  - { id: 1477507499, name: "Zoho Invoice" }

mas_upgrade_all_apps: no
mas_signin_dialog: no

dockutil_url: https://raw.githubusercontent.com/kcrawford/dockutil/master/scripts/dockutil
dockutil_install_path: /usr/local/bin/dockutil

dockitems_remove_all: false

dockitems_disabled:
  - Mail
  - Safari
  - Siri
  - Contacts
  - Notes
  - Reminders
  - Maps
  - Photos
  - Messages
  - FaceTime
  - iTunes
  - App Store
  - System Preferences
  - Calendar
  - Terminal

dockitems_enabled:
  - name: Launchpad
    path: "/Applications/Launchpad.app"
    pos: 1
  - name: Commander One
    path: "/Applications/SetApp/Commander One.app"
    pos: 2
  - name: Spark
    path: "/Applications/Spark.app"
    pos: 3
  - name: Calendar
    path: "/System/Applications/Calendar.app"
    pos: 4
  - name: OmniFocus
    path: "/Applications/OmniFocus.app"
    pos: 5
  - name: Basecamp 3
    path: "/Applications/Basecamp 3.app"
    pos: 6
  - name: Tweetbot
    path: "/Applications/Tweetbot.app"
    pos: 7
  - name: Visual Studio Code
    path: "/Applications/Visual Studio Code.app"
    pos: 8
  - name: SQLPro Studio
    path: "/Applications/SetApp/SQLPro Studio.app"
    pos: 9

dotfiles_repo: "https://github.com/ringods/dotfiles.git"
dotfiles_repo_version: master
dotfiles_repo_local_destination: "~/Projects/personal/dotfiles"
dotfiles_repo_accept_hostkey: true
dotfiles_home: "~"
dotfiles_files:
  - .gitconfig
  - .gitignore
  - .zshrc.local
