---
roles:
  - name: elliotweiser.osx-command-line-tools
    version: 2.3.0
  - name: viasite-ansible.zsh
    version: v3.7.8

collections:
  - name: community.general
    version: 10.0.1
  - name: geerlingguy.mac
    version: 4.0.2
