---
roles:
  - name: elliotweiser.osx-command-line-tools
    version: 2.3.0
  - name: pridkett.fish
    scm: git
    src: https://github.com/pridkett/ansible-role-fish.git
    version: master

collections:
  - name: community.general
    version: 10.0.1
  - name: geerlingguy.mac
    version: 4.0.2
