---
- hosts: localhost
  connection: local

  vars_files:
    - config.yml

  roles:
    - role: elliotweiser.osx-command-line-tools
    - role: geerlingguy.homebrew
      tags: ["homebrew"]
    - role: geerlingguy.mas
      when: mas_installed_apps
      tags: ["appstore"]
    - role: geerlingguy.dock
    - role: viasite-ansible.zsh
    - role: geerlingguy.dotfiles
