---
- name: Configure AtrisoBook2022
  hosts: AtrisoBook2022

  vars_files:
    - vars.yml

  vars:
    fish:
      set_default_shell: true
      install_fisher: true
      fisher_plugins:
        - halostatue/fish-brew@v3

  roles:
    - role: mac-minimal
    - role: pridkett.fish
    - role: mac-common
    - role: mac-work
