---
- hosts: AtrisoBook2020

  vars_files:
    - vars.yml

  roles:
    - role: mac-minimal
    - role: mac-common
    - role: mac-personal
    #- role: geerlingguy.mac.mas
    #  when: mas_installed_apps
    #  tags: ["appstore"]
    # - role: geerlingguy.mac.dock
    # - role: viasite-ansible.zsh
    # - role: geerlingguy.dotfiles
