---
galaxy_info:
  author: Ringo De Smet
  description: Configures the PiKVM with DNSimple based LetsEncrypt certbot configuration
  company: None

  license: MIT

  min_ansible_version: 2.2

  platforms:
    - name: GenericLinux
      versions:
        - all
        - any

  galaxy_tags:
    - raspberrypi
    - kvm
    - system
    - configuration

dependencies: []
