---
galaxy_info:
  author: Ringo De Smet
  description: Common macOS setup for both MacBook Pro machines.
  company: None

  license: MIT

  min_ansible_version: "9.0"

  platforms:
    - name: MacOSX
      versions:
        - "all"

  galaxy_tags:
    - osx
    - configuration

dependencies:
  - role: geerlingguy.mac.homebrew
    vars:
      homebrew_taps:
        - dagger/tap
        - derailed/k9s
        - hashicorp/tap
        - buo/cask-upgrade
        - pulumi/tap
        - updatecli/updatecli
        - goreleaser/tap
      homebrew_installed_packages:
        - asciidoctor
        - awscli
        - azure-cli
        - chezmoi
        - cilium-cli
        - d2
        - direnv
        - exercism
        - fastfetch
        - gh
        - gnu-tar
        - gnupg
        - graphviz
        - gzip
        - helm
        - httpie
        - jq
        - mise
        - pinentry-mac
        - pre-commit
        - protobuf
        - pstree
        - rustup
        - starship
        - terraform
        - uv
        - watch
        - dagger/tap/dagger
        - derailed/k9s/k9s
        - pulumi/tap/pulumi
        - pulumi/tap/crd2pulumi
        - pulumi/tap/kube2pulumi
        - pulumi/tap/pulumictl
        - updatecli/updatecli/updatecli
#      homebrew_uninstalled_packages:
      homebrew_cask_appdir: /Applications
      homebrew_cask_apps:
        - 1password
        - 1password-cli
        - affinity-designer
        - affinity-photo
        - affinity-publisher
        - alfred
        - balenaetcher
        - clickup
        - corretto
        - deskpad
        - discord
        - element
        - elgato-stream-deck
        - firefox
        - focusrite-control
        - font-roboto-mono-nerd-font
        - gitbutler
        - ghostty
        - google-chrome
        - google-drive
        - insomnia
        - jetbrains-toolbox
        - little-snitch
        - melodics
        - micro-snitch
        - obsidian
        - raindropio
        - raspberry-pi-imager
        - setapp
        - slack
        - spotify
        - surfshark
        - thunderbird
        - vlc
        - visual-studio-code
        - zoom
      homebrew_cask_uninstalled_apps:
        - goreleaser/tap/goreleaser
        - obs
  - role: geerlingguy.mac.mas
    vars:
      mas_installed_apps:
        - id: 682658836
          name: "GarageBand"
        - id: 408981434
          name: "iMovie"
        - id: 899247664
          name: "Testflight"
        - id: 409201541
          name: "Pages"
        - id: 409203825
          name: "Numbers"
        - id: 409183694
          name: "Keynote"
        - id: 403504866
          name: "PCalc"
        - id: 1659154653
          name: "Mona"
        - id: 441258766
          name: "Magnet"
#      mas_uninstalled_apps:
