---
galaxy_info:
  author: Ringo De Smet
  description: Common macOS setup for both MacBook Pro machines.
  company: None

  license: MIT

  min_ansible_version: 2.2

  platforms:
    - name: MacOSX
      versions:
        - "all"

  galaxy_tags:
    - osx
    - configuration

dependencies:
  - role: geerlingguy.mac.homebrew
    vars:
      homebrew_taps:
        - dagger/tap
        - derailed/k9s
        - hashicorp/tap
        - buo/cask-upgrade
        - pulumi/tap
        - updatecli/updatecli
      homebrew_installed_packages:
        - antidote
        - asciidoctor
        - awscli
        - azure-cli
        - chezmoi
        - d2
        - direnv
        - exercism
        - fastfetch
        - gh
        - gnu-tar
        - gnupg
        - go
        - graphviz
        - gzip
        - helm
        - httpie
        - jq
        - pinentry-mac
        - plantuml
        - poetry
        - pre-commit
        - protobuf
        - pstree
        - starship
        # - thunderbird
        - volta
        - watch
        - dagger/tap/dagger
        - derailed/k9s/k9s
        - pulumi/tap/pulumi
        - pulumi/tap/crd2pulumi
        - pulumi/tap/kube2pulumi
        - pulumi/tap/pulumictl
        - updatecli/updatecli/updatecli
      homebrew_cask_appdir: /Applications
      homebrew_cask_apps:
        - 1password
        - 1password-cli
        - alfred
        - clickup
        - corretto
        - deskpad
        - discord
        - element
        - elgato-stream-deck
        - firefox
        - focusrite-control
        - font-roboto-mono-nerd-font
        - gitbutler
        - ghostty
        - google-chrome
        - google-drive
        - insomnia
        - obs
        - obsidian
        - raindropio
        - setapp
        - signal
        - slack
        - spotify
        - surfshark
        - tidal
        - vlc
        - visual-studio-code
        - zed
        - zoom
      homebrew_cask_uninstalled_apps:
        - warp
  - role: geerlingguy.mac.mas
    vars:
      mas_installed_apps:
        - id: 409201541
          name: "Pages"
        - id: 409203825
          name: "Numbers"
        - id: 409183694
          name: "Keynote"
        - id: 403504866
          name: "PCalc"
        - id: 6444602274
          name: "Ivory"
        - id: 441258766
          name: "Magnet"
        - id: 310633997
          name: "WhatsApp Messenger"
