---
galaxy_info:
  author: Ringo De Smet
  description: Work related macOS setup.
  company: None

  license: MIT

  min_ansible_version: 2.2

  platforms:
    - name: MacOSX
      versions:
        - 'all'

  galaxy_tags:
    - osx
    - configuration

dependencies:
  - role: geerlingguy.mac.homebrew
    vars:
      homebrew_taps:
        - isen-ng/dotnet-sdk-versions
      #homebrew_installed_packages:
      homebrew_uninstalled_packages:
        - hashicorp/tap/packer
      homebrew_cask_appdir: /Applications
      homebrew_cask_apps:
        - google-cloud-sdk
        - microsoft-teams
        - isen-ng/dotnet-sdk-versions/dotnet-sdk6-0-400
        - isen-ng/dotnet-sdk-versions/dotnet-sdk7-0-200
      homebrew_cask_uninstalled_apps:
        - zed
  # - role: geerlingguy.mac.mas
  #   vars:
  #     mas_uninstalled_apps:
  #       - id: 824171161
  #         name: "Affinity Designer"
  #       - id: 406056744
  #         name: "Evernote"
  #       - id: 682658836
  #         name: "GarageBand"
  #       - id: 408981434
  #         name: "iMovie"
  #       - id: 899247664
  #         name: "Testflight"
