---
galaxy_info:
  author: Ringo De Smet
  description: Work related macOS setup.
  company: None

  license: MIT

  min_ansible_version: "9.0"

  platforms:
    - name: MacOSX
      versions:
        - "all"

  galaxy_tags:
    - osx
    - configuration

dependencies:
  - role: geerlingguy.mac.homebrew
    vars:
      homebrew_taps:
        - isen-ng/dotnet-sdk-versions
      # homebrew_installed_packages:
      homebrew_uninstalled_packages:
        - hashicorp/tap/packer
      homebrew_cask_appdir: /Applications
      homebrew_cask_apps:
        - docker
        - google-cloud-sdk
        - microsoft-teams
        - isen-ng/dotnet-sdk-versions/dotnet-sdk8-0-400
      homebrew_cask_uninstalled_apps:
        - isen-ng/dotnet-sdk-versions/dotnet-sdk7-0-400
  - role: geerlingguy.mac.dock
