---
galaxy_info:
  author: Ringo De Smet
  description: Minimal macOS setup.
  company: None

  license: MIT

  min_ansible_version: 2.2

  platforms:
    - name: MacOSX
      versions:
        - 'all'

  galaxy_tags:
    - osx
    - configuration

dependencies:
  - role: geerlingguy.mac.homebrew
    vars:
      homebrew_cask_appdir: /Applications
      homebrew_cask_apps:
        - google-cloud-sdk
      homebrew_cask_uninstalled_apps:
        - balenaetcher
        - dropbox
        - trainerroad
