---
galaxy_info:
  author: Ringo De Smet
  description: Minimal macOS setup.
  company: None

  license: MIT

  min_ansible_version: 2.2

  platforms:
    - name: MacOSX
      versions:
        - 'all'

  galaxy_tags:
    - osx
    - configuration

dependencies:
  - role: geerlingguy.mac.homebrew
    vars:
      homebrew_taps:
        - isen-ng/dotnet-sdk-versions
      #homebrew_installed_packages:
      homebrew_uninstalled_packages:
        - hashicorp/tap/packer
      homebrew_cask_appdir: /Applications
      homebrew_cask_apps:
        - google-cloud-sdk
        - isen-ng/dotnet-sdk-versions/dotnet-sdk6-0-400
        - isen-ng/dotnet-sdk-versions/dotnet-sdk7-0-200
      homebrew_cask_uninstalled_apps:
        - balenaetcher
        - dropbox
        - little-snitch
        - micro-snitch
        - paragon-extfs
        - raspberry-pi-imager
        - trainerroad
