---
galaxy_info:
  author: Ringo De Smet
  description: macOS setup.
  company: Hardes

  license: MIT

  min_ansible_version: "9.0"

  platforms:
    - name: MacOSX
      versions:
        - "all"

  galaxy_tags:
    - osx
    - configuration

dependencies:
  - role: geerlingguy.mac.homebrew
    vars:
      # homebrew_taps:
      # homebrew_installed_packages:
      # homebrew_uninstalled_packages:
      homebrew_cask_appdir: /Applications
      homebrew_cask_apps:
        - docker
        - google-cloud-sdk
        - microsoft-teams
      # homebrew_cask_uninstalled_apps:
  - role: geerlingguy.mac.dock
